name: My First Workflow

on: push


jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: check out
              uses: actions/checkout@v4

            - name: List and Read files
              run: |
                echo "My first github actions job"
                ls -ltra
                cat RADME.md

            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover, I am a dragon RAWR" >> dragon.txt

            # - name: Read files
            #   run: cat README.md