name: Generate ASCII artwork

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: Install cowsay
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

            - name: upload artifact
              uses: actions/upload-artifact@v7
              with:
                name: dragontextfile
                path: dragon.txt
            
            - name: Sleep for 30 secs
              run: sleep 30
              
    test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
            - name: Sleep for 10s
              run: sleep 10

            - name: Download artifact
              uses: actions/download-artifact@v8
              with:
                name: dragontextfile
            
            - name: Display structure of downloaded files
              run: ls -R

            - name: test file exists
              run: grep -i "dragon" dragon.txt

    deploy_job:
        runs-on: ubuntu-latest
        needs: [build_job, test_job]
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v8
              with:
                name: dragontextfile
                
            - name: read file
              run: cat dragon.tt

            - name: deploy
              run: echo Deploying...